name: Regression Test the Grader
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v7
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken()
            coredemo.setOutput('id_token', id_token)
      - name: Retrieve regression test matrix
        run: |
          response=$(curl -H "Authorization: ${{ steps.idtoken.outputs.id_token }}" https://khoury-classroom-dev.ngrok.pizza/api/autograder/regression-tests)
          echo "matrix=$response" >> $GITHUB_ENV
        shell: bash

  smoke-test:
    name: Submit and Grade Assignment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          path: submission

      - name: Collect Submission and Run Grader
        uses: neu-se/autograder-action@main
        with:
          grading_server: 'https://khoury-classroom-dev.ngrok.pizza'
          handout_repo: 'pawtograder/example-assignment-java-handout'
